#!/bin/sh

set -e

printusage() {
         echo "\n       ERROR: 1 or 3 arguments required.\n\n"

         echo "Usage: $0 initdb [LANG EN]"
         echo "       $0 newlocale [LANG EN]"
         echo ""
         echo "       $0 initdb en_US UTF-8"
         echo "       $0 newlocale en_GB UTF-8"
         echo "\n"
         echo "       If LANG and EN are not provided en_US UTF-8 is used as defaults.\n"
}

#
# Usage checks
#

if [ "$1" = "newlocale" -a \( -z "$2" -o -z "$3" \) ]; then

 printusage
 exit

fi

#
# Set locale defaults
#

if [ ! -z "$2" ]; then
  LOCLANG="$2"
else
  LOCLANG="en_US"
fi

if [ ! -z "$3" ]; then
  LOCEN="$3"
else
  LOCEN="UTF-8"
fi

#
# Environment variables
# Locale

LOC="$LOCLANG.$LOCEN"

export LANG=$LOC
export I18NPATH=$SNAP/usr/share/i18n
export LOCPATH=$SNAP_USER_DATA/locales

# PostgreSQL

DATA_DIR="$SNAP_USER_DATA/data"
LOG_DIR="$SNAP_USER_DATA/logs"
BASE_DIR="$DATA_DIR/base"

#
# Functions
#


localegen() {
[ -e "$LOCPATH" ] || mkdir "$LOCPATH"

if [ ! -e $LOCPATH/$LOC ]; then
echo "Generating a new locale in $LOCPATH/$LOC..."
  localedef --prefix=$LOCPATH -f $LOCEN -i $LOCLANG $LOCPATH/$LOC
fi
}


pginit() {
echo "Checking if data directory exists. If not, it will be created."
[ -e "$DATA_DIR" ] || mkdir "$DATA_DIR"

echo "Checking if log directory exists. If not, it will be created."
[ -e "$LOG_DIR" ] || mkdir "$LOG_DIR"

echo "Checking if initdb has already been run before. If not, a new cluster will be created."
[ -e "$BASE_DIR" ] || $SNAP/usr/bin/initdb -D $DATA_DIR
}

#
# Main script
#

case $1 in
      initdb)
	 localegen
         pginit
         ;;
      newlocale)
         localegen
         ;;
      *)
         printusage
esac

